openapi: '3.0.2'
info:
  title: Mangain Rest API
  version: '1.0'
servers:
  - url: http://128.199.79.183:5000

paths:
  /api/home:
    get:
      responses:
        '200':
          description: OK

  /api/kiryuu-new-update/{page}:
    get:
      description: ''
      parameters:
        - in: path
          name: page
          required: true
          schema:
            type: integer
            minimum: 1
      
      responses:
        '200':
          description: OK
